<!doctype html>
<html lang="en" data-theme="light"><head>
@include('partials.language')
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>AgriSentry — Account settings</title>
<link rel="icon" href="/images/anuvimco-logo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<script>try { document.documentElement.dataset.theme = localStorage.getItem('agrisentry-theme') || 'light'; } catch(e) {}</script>
<style>
@include('partials.design-system')
.account-main{max-width:1180px;margin:auto;padding:32px 24px 64px;width:100%}.account-nav{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:28px}.account-brand{display:flex;gap:10px;align-items:center;font-weight:800;font-size:18px;margin-right:auto;color:var(--text-0)}.account-brand img{width:38px;height:38px;object-fit:contain}.settings-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);gap:24px;align-items:start}.account-main h1{font-size:28px;letter-spacing:-.6px;margin-bottom:8px}.account-main h2{font-size:17px;margin-bottom:8px}.account-main p{line-height:1.65}.account-main form{margin-top:18px}.account-main form>.btn,.account-main form>button{margin-top:18px}.account-main label{display:block;color:var(--text-2);font-size:13px;font-weight:600;margin:14px 0 7px}.account-main input:not([type=checkbox]),.account-main select{width:100%;background:var(--bg-raised);color:var(--text-0);border:1px solid var(--border);border-radius:var(--radius-sm);padding:11px 12px;font:inherit;min-height:42px}.account-main input[type=checkbox]{accent-color:var(--green);width:18px;height:18px;vertical-align:middle;margin-right:8px}.account-main button{font:inherit}.account-main button:not(.btn){background:var(--green);color:white;border:0;border-radius:var(--radius-sm);padding:10px 16px;font-weight:600;cursor:pointer}.account-main button:disabled{opacity:.5;cursor:default}.account-main fieldset{border:1px solid var(--border);border-radius:var(--radius-sm);padding:12px 16px;margin:12px 0}.account-main legend{font-weight:600;font-size:13px;padding:0 6px}.account-main td,.account-main th{padding:12px;text-align:left;border-bottom:1px solid var(--border);font-size:13px}.account-main .message{background:var(--green-bg);color:var(--green-dk);border-radius:var(--radius-sm);padding:12px 16px;margin-bottom:18px}.account-main .error{background:var(--red-bg);color:var(--red);padding:12px 16px;border-radius:var(--radius-sm);margin-bottom:18px}.settings-links{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}#permissions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}#permissions form{padding:20px;background:var(--bg-card);border:1px solid var(--border);border-radius:var(--radius)}.account-main section{margin-bottom:24px}.account-main .table-wrap{background:var(--bg-card);border:1px solid var(--border);border-radius:var(--radius);margin:16px 0}
@media(max-width:760px){.settings-grid,#permissions{grid-template-columns:1fr}.account-main{padding:20px 16px 40px}.account-brand{width:100%;margin-bottom:8px}}
.settings-sections{display:flex;gap:10px;flex-wrap:wrap;margin:0 0 24px}.settings-grid{grid-template-columns:1fr;max-width:820px}.settings-subtitle{font-size:14px;color:var(--text-1);border-top:1px solid var(--border);padding-top:18px;margin-top:8px}#profile,#security,#administration{scroll-margin-top:20px}.settings-grid .panel-body{padding:24px}.settings-grid form>.btn{min-width:180px}
</style></head><body><div class="app"><main class="account-main">
<nav class="account-nav" aria-label="Account navigation"><a class="account-brand" href="{{ auth()->check() ? '/agrisentry' : '/login' }}"><img src="/images/agrisentry-logo-v2-transparent.png" alt="">AgriSentry</a>
@auth<a class="btn btn-sm" href="/agrisentry">Dashboard</a><a class="btn btn-sm" href="/settings">Settings</a>@if(auth()->user()->isAdmin())<a class="btn btn-sm" href="/admin/users">Manage users</a><a class="btn btn-sm" href="/admin/access">Access &amp; activity</a>@endif
@else<a class="btn btn-sm" href="/login">Back to sign in</a>@endauth</nav>
@if(session('status'))<p class="message" role="status">{{ session('status') }}</p>@endif
@if($errors->any())<div class="error" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
@yield('content')
</main></div><script src="/js/navigation-feedback.js" defer></script></body></html>
