ServerRoot "C:/xampp/apache"
Listen 127.0.0.1:8000
ServerName localhost
PidFile "C:/xampp/htdocs/Agrisentry/Agrisentry/local-server/apache.pid"
ErrorLog "C:/xampp/htdocs/Agrisentry/Agrisentry/local-server/error.log"
LogLevel warn
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule mime_module modules/mod_mime.so
LoadModule dir_module modules/mod_dir.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule env_module modules/mod_env.so
LoadFile "C:/xampp/php/libcrypto-3-x64.dll"
LoadFile "C:/xampp/php/libssl-3-x64.dll"
LoadFile "C:/xampp/php/libssh2.dll"
LoadFile "C:/xampp/php/php8ts.dll"
LoadFile "C:/xampp/php/libpq.dll"
LoadFile "C:/xampp/php/libsqlite3.dll"
LoadModule php_module "C:/xampp/php/php8apache2_4.dll"
PHPINIDir "C:/xampp/htdocs/Agrisentry/Agrisentry/local-server"
TypesConfig conf/mime.types
DocumentRoot "C:/xampp/htdocs/Agrisentry/Agrisentry/public"
DirectoryIndex index.php
<Directory />
    AllowOverride None
    Require all denied
</Directory>
<Directory "C:/xampp/htdocs/Agrisentry/Agrisentry/public">
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
ServerTokens Prod
ServerSignature Off
Timeout 60

LoadModule filter_module modules/mod_filter.so
LoadModule deflate_module modules/mod_deflate.so
AddOutputFilterByType DEFLATE text/html text/plain text/css application/javascript application/json image/svg+xml
